CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
DATASET:
  DATASET: mpii
  DATA_FORMAT: jpg
  FLIP: true
  HYBRID_JOINTS_TYPE: ''
  ROOT: ''
  ROT_FACTOR: 30
  SCALE_FACTOR: 0.25
  SELECT_DATA: false
  TEST_SET: valid
  TRAIN_SET: train
DATA_DIR: ''
DEBUG:
  DEBUG: false
  SAVE_BATCH_IMAGES_GT: false
  SAVE_BATCH_IMAGES_PRED: false
  SAVE_HEATMAPS_GT: false
  SAVE_HEATMAPS_PRED: false
GPUS: '0'
LOG_DIR: ''
LOSS:
  USE_TARGET_WEIGHT: true
MODEL:
  EXTRA: !!python/object/new:easydict.EasyDict
    dictitems:
      DECONV_WITH_BIAS: false
      FINAL_CONV_KERNEL: 1
      HEATMAP_SIZE: &id001
      - 64
      - 64
      NUM_DECONV_FILTERS: &id002
      - 256
      - 256
      - 256
      NUM_DECONV_KERNELS: &id003
      - 4
      - 4
      - 4
      NUM_DECONV_LAYERS: 3
      NUM_LAYERS: 50
      SIGMA: 2
      TARGET_TYPE: gaussian
    state:
      DECONV_WITH_BIAS: false
      FINAL_CONV_KERNEL: 1
      HEATMAP_SIZE: *id001
      NUM_DECONV_FILTERS: *id002
      NUM_DECONV_KERNELS: *id003
      NUM_DECONV_LAYERS: 3
      NUM_LAYERS: 50
      SIGMA: 2
      TARGET_TYPE: gaussian
  IMAGE_SIZE:
  - 256
  - 256
  INIT_WEIGHTS: true
  NAME: pose_resnet
  NUM_JOINTS: 16
  PRETRAINED: ''
OUTPUT_DIR: ''
PRINT_FREQ: 20
TEST:
  BATCH_SIZE: 32
  BBOX_THRE: 1.0
  COCO_BBOX_FILE: ''
  FLIP_TEST: false
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.0
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.5
  POST_PROCESS: true
  SHIFT_HEATMAP: true
  USE_GT_BBOX: false
TRAIN:
  BATCH_SIZE: 32
  BEGIN_EPOCH: 0
  CHECKPOINT: ''
  END_EPOCH: 140
  GAMMA1: 0.99
  GAMMA2: 0.0
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 110
  MOMENTUM: 0.9
  NESTEROV: false
  OPTIMIZER: adam
  RESUME: false
  SHUFFLE: true
  WD: 0.0001
WORKERS: 4
